name: ebook_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0" # Adjust to support null safety

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Updated version with null safety
  provider: ^6.1.2 # Updated version with null safety
  path_provider: ^2.1.4 # Updated version with null safety
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
